import type { Metadata } from "next"
import { createClient } from "@supabase/supabase-js"
import CssBaseline from "@mui/material/CssBaseline"
import Box from "@mui/material/Box"

import { Header } from "@/src/components/Header"
import { Providers } from "@/src/components/Providers"
import { Footer } from "@/src/components/Footer"

// Create a single supabase client for interacting with your database
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <CssBaseline />

      <html lang="en">
        <Box
          component="body"
          sx={{
            backgroundColor: "#F3F8EE", // theme.palette.background.default,
          }}
        >
          <Providers>
            <Header />

            {children}

            <Footer />
          </Providers>
        </Box>
      </html>
    </>
  )
}
